// <auto-generated />
using System;
using DomainService.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DomainService.Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainService.Core.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(682),
                            Name = "Angola",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(682)
                        },
                        new
                        {
                            Id = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(687),
                            Name = "Botswana",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(688)
                        },
                        new
                        {
                            Id = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(689),
                            Name = "Canada",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(690)
                        },
                        new
                        {
                            Id = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(691),
                            Name = "Dominica",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(691)
                        });
                });

            modelBuilder.Entity("DomainService.Core.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Province", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5be29c4a-8d2d-4408-b4af-252c04740c53"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(694),
                            Name = "Bengo",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(695)
                        },
                        new
                        {
                            Id = new Guid("754d8eff-ba27-486a-8535-6ca72b9223d1"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(697),
                            Name = "Cuanza Sul",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(698)
                        },
                        new
                        {
                            Id = new Guid("85116026-ba51-4cec-b539-eeac2ed56a29"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(699),
                            Name = "Cunene",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(699)
                        },
                        new
                        {
                            Id = new Guid("0c11f6cf-f351-457f-88df-6ba85f8c5d06"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(701),
                            Name = "Huambo",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(701)
                        },
                        new
                        {
                            Id = new Guid("c3d9d664-8e16-4df0-adfd-97955ba85b88"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(704),
                            Name = "Luanda",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(705)
                        },
                        new
                        {
                            Id = new Guid("0b2457eb-871c-4a55-8284-2886723d81af"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(708),
                            Name = "Malanje",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(708)
                        },
                        new
                        {
                            Id = new Guid("ee0d1243-e724-4c36-a1a5-809600833e3b"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(709),
                            Name = "Moxico",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(709)
                        },
                        new
                        {
                            Id = new Guid("52d55d06-39e3-47ee-ad31-06a037d45fd6"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(712),
                            Name = "Bengo23",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(712)
                        },
                        new
                        {
                            Id = new Guid("d18372bb-c0e2-439c-86b7-39be2be70322"),
                            CountryId = new Guid("6816ee4a-91f3-4cae-a5c3-3285ee87db0d"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(714),
                            Name = "Namibe",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(714)
                        },
                        new
                        {
                            Id = new Guid("7fdf47b4-788d-49ff-ac5a-2c42f659d4dc"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(716),
                            Name = "Gaborone",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(716)
                        },
                        new
                        {
                            Id = new Guid("c9f9a5c3-433a-49bb-b57a-c63fab7a9cf7"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(718),
                            Name = "Cuanza Sul",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(718)
                        },
                        new
                        {
                            Id = new Guid("671bdb0f-3209-4bf6-b7d8-c5b46f97042c"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(719),
                            Name = "Francistown",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(720)
                        },
                        new
                        {
                            Id = new Guid("137c69c7-7c73-4be4-947b-3e4630b6191a"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(723),
                            Name = "Jwaneng",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(723)
                        },
                        new
                        {
                            Id = new Guid("b0f867e0-cad8-4a80-8e2d-67150d1ed2a3"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(724),
                            Name = "Orapa",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(724)
                        },
                        new
                        {
                            Id = new Guid("10e4d238-0535-4643-b235-ab8b50657abd"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(726),
                            Name = "Malanje",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(726)
                        },
                        new
                        {
                            Id = new Guid("d936d8c5-eef9-429e-a602-d2181437c7ae"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(727),
                            Name = "Kanye",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(728)
                        },
                        new
                        {
                            Id = new Guid("da5273a6-794f-4841-958f-e3a0494aa3cd"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(729),
                            Name = "Ramotswa",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(729)
                        },
                        new
                        {
                            Id = new Guid("9b522774-696e-42cc-83ac-ebab319bdb07"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(731),
                            Name = "Mochudi",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(731)
                        },
                        new
                        {
                            Id = new Guid("0ab8ec37-d69c-4ffd-a145-2c9d425177fe"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(733),
                            Name = "Mochudi2",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(733)
                        },
                        new
                        {
                            Id = new Guid("8841be8f-b368-4d51-abb3-8526d148ba89"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(734),
                            Name = "Mochudi3",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(735)
                        },
                        new
                        {
                            Id = new Guid("8ec1304f-d749-4d37-aca8-9cd68bd129a0"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(737),
                            Name = "Mochudias",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(738)
                        },
                        new
                        {
                            Id = new Guid("3ecf9f54-c39d-43a5-a965-3beb55662435"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(739),
                            Name = "Mochudids",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(739)
                        },
                        new
                        {
                            Id = new Guid("e7438ca0-b960-46b2-92ec-b3db2b135590"),
                            CountryId = new Guid("2d21c50c-f170-4fcb-af22-db320c190193"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(740),
                            Name = "Mochudixc",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(741)
                        },
                        new
                        {
                            Id = new Guid("216ec99a-fa63-4b96-8e63-c2e2098b4f6b"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(742),
                            Name = "Gaborone",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(742)
                        },
                        new
                        {
                            Id = new Guid("7f76919e-2ec9-474d-9e3e-2fa7324ff6ad"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(743),
                            Name = "Cuanza Sul",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(744)
                        },
                        new
                        {
                            Id = new Guid("ef13fb36-0ec5-46c5-b8b1-7fce884d0d81"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(745),
                            Name = "Francistown",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(746)
                        },
                        new
                        {
                            Id = new Guid("a158e2fd-edeb-4fc8-bec1-fac607783c80"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(747),
                            Name = "Jwaneng",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(747)
                        },
                        new
                        {
                            Id = new Guid("a13ebfe7-ae4d-4bb7-9b40-731244a24fba"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(748),
                            Name = "Orapa",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(749)
                        },
                        new
                        {
                            Id = new Guid("be0bf73c-2ae5-4e49-9b4c-983596835a18"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(751),
                            Name = "Malanje",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(752)
                        },
                        new
                        {
                            Id = new Guid("fd3cc87e-6c3e-44cf-8c4f-f16dcd51d534"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(753),
                            Name = "Kanye",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(753)
                        },
                        new
                        {
                            Id = new Guid("0fba0d27-436b-4875-88d9-7d60716815f3"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(754),
                            Name = "Ramotswa",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(755)
                        },
                        new
                        {
                            Id = new Guid("3122d8cf-aa94-4672-a062-207473aa14d0"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(756),
                            Name = "Mochudi",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(756)
                        },
                        new
                        {
                            Id = new Guid("f683baa7-26a7-4859-925b-636493685127"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(758),
                            Name = "Mochudi2",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(758)
                        },
                        new
                        {
                            Id = new Guid("5c0420cd-679b-49ff-a864-4381041ba37a"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(760),
                            Name = "Mochudi3",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(760)
                        },
                        new
                        {
                            Id = new Guid("740e742f-35b6-4fd4-a42d-fb965a474d01"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(761),
                            Name = "Mochudias",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(762)
                        },
                        new
                        {
                            Id = new Guid("548d2988-2ded-48e8-b644-7d60783bedf2"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(763),
                            Name = "Mochudids",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(763)
                        },
                        new
                        {
                            Id = new Guid("f89e8221-c6e9-4972-ada6-836ed5ff4d2b"),
                            CountryId = new Guid("2357538a-fb77-483c-b74d-193d3381e067"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(766),
                            Name = "Mochudixc",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(766)
                        },
                        new
                        {
                            Id = new Guid("d5b08d0a-f49e-49f1-91a8-002433ae9d0e"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(767),
                            Name = "Marigot",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(768)
                        },
                        new
                        {
                            Id = new Guid("99b5cbf1-bab5-473a-8245-07b9945f3225"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(769),
                            Name = "Castle Bruce",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(769)
                        },
                        new
                        {
                            Id = new Guid("fcb6667b-c680-41a1-864d-1206101b596c"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(771),
                            Name = "Roseau",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(771)
                        },
                        new
                        {
                            Id = new Guid("7c6008df-0327-4d20-9b59-dc9eee9f5e4e"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(772),
                            Name = "Portsmouth",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(772)
                        },
                        new
                        {
                            Id = new Guid("faa67e87-6666-4592-b589-0a1ebf7635d6"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(774),
                            Name = "Saint Joseph",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(774)
                        },
                        new
                        {
                            Id = new Guid("6d9c1649-cf61-46c3-8a66-a06da942bf60"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(775),
                            Name = "Pointe Michel",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(776)
                        },
                        new
                        {
                            Id = new Guid("20b36f86-e588-473b-836a-447b8afc5589"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(777),
                            Name = "Moxico",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(777)
                        },
                        new
                        {
                            Id = new Guid("48591b8f-9c5a-4553-9a98-11ddf224d0f9"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(780),
                            Name = "Soufrière",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(780)
                        },
                        new
                        {
                            Id = new Guid("d7f44f5f-ea1b-4e17-9cb1-87315caba86a"),
                            CountryId = new Guid("54a4811c-01d9-4f8f-8057-d3cc9abb3c31"),
                            CreatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(781),
                            Name = "Berekua",
                            UpdatedOn = new DateTime(2023, 1, 25, 16, 56, 15, 692, DateTimeKind.Utc).AddTicks(782)
                        });
                });

            modelBuilder.Entity("DomainService.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAgreeWorkForFood")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DomainService.Core.Domain.Entities.Province", b =>
                {
                    b.HasOne("DomainService.Core.Domain.Entities.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DomainService.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("DomainService.Core.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.OwnsOne("DomainService.ValueObjects.Email.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("DomainService.ValueObjects.Password.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("DomainService.Core.Domain.Entities.Country", b =>
                {
                    b.Navigation("Provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
