version: '3.4'

services:
  domainservice.webapi:
    image: ${DOCKER_REGISTRY-}domainservicewebapi
    build:
      context: .
      dockerfile: Services/DomainService/DomainService.WebApi/Dockerfile
    depends_on:
      - postgres

  domainservice.webapi.bff:
    image: ${DOCKER_REGISTRY-}domainservicewebapi.bff
    build:
      context: .
      dockerfile: Bff/BaseBff/Dockerfile
    depends_on:
      - domainservice.webapi

  registrationclient.app:
    image: ${DOCKER_REGISTRY-}registrationclient.app
    build:
        context: ./Client/RegistrationClientApp
        dockerfile: Dockerfile

  postgres:
    restart: always
    image: postgres

  postgres-admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres

volumes:
  node_modules: